### ISSUE TITLE
Game Library page

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/BoardwalkGames#8]
**User Story:** 
As a regular visitor, I would like a specific page to look at new releases as well as to be able to easily find popular classics. 

**Acceptance Criteria:**

- [x] The homepage has a clear link to the page which holds the new and classic games information.
- [x] The games page is laid out to give product images alongside details of the games.

**Tasks:**

- [x] Create a new page to house the games information.
- [x] Make sure the link to the page from the homepage is clear and easy to find.
- [x] Create a layout which includes pictures and text details.
